// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: localbroker/v1/localbroker.proto

package localbrokerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevokeTimedGrantResponse_Status int32

const (
	RevokeTimedGrantResponse_STATUS_UNSPECIFIED RevokeTimedGrantResponse_Status = 0
	RevokeTimedGrantResponse_STATUS_REVOKED     RevokeTimedGrantResponse_Status = 1
	RevokeTimedGrantResponse_STATUS_NOT_FOUND   RevokeTimedGrantResponse_Status = 2
)

// Enum value maps for RevokeTimedGrantResponse_Status.
var (
	RevokeTimedGrantResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_REVOKED",
		2: "STATUS_NOT_FOUND",
	}
	RevokeTimedGrantResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_REVOKED":     1,
		"STATUS_NOT_FOUND":   2,
	}
)

func (x RevokeTimedGrantResponse_Status) Enum() *RevokeTimedGrantResponse_Status {
	p := new(RevokeTimedGrantResponse_Status)
	*p = x
	return p
}

func (x RevokeTimedGrantResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RevokeTimedGrantResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_localbroker_v1_localbroker_proto_enumTypes[0].Descriptor()
}

func (RevokeTimedGrantResponse_Status) Type() protoreflect.EnumType {
	return &file_localbroker_v1_localbroker_proto_enumTypes[0]
}

func (x RevokeTimedGrantResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RevokeTimedGrantResponse_Status.Descriptor instead.
func (RevokeTimedGrantResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_localbroker_v1_localbroker_proto_rawDescGZIP(), []int{3, 0}
}

type GrantTimedSudoersRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	GrantId                    string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	DeviceId                   string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TargetUsername             string                 `protobuf:"bytes,3,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	RoleName                   string                 `protobuf:"bytes,4,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	DurationMillis             int64                  `protobuf:"varint,5,opt,name=duration_millis,json=durationMillis,proto3" json:"duration_millis,omitempty"`
	DeniedUsernames            []string               `protobuf:"bytes,6,rep,name=denied_usernames,json=deniedUsernames,proto3" json:"denied_usernames,omitempty"`
	AllowedUidRanges           []string               `protobuf:"bytes,7,rep,name=allowed_uid_ranges,json=allowedUidRanges,proto3" json:"allowed_uid_ranges,omitempty"`
	RequestExpiresAtUnixMillis *int64                 `protobuf:"varint,8,opt,name=request_expires_at_unix_millis,json=requestExpiresAtUnixMillis,proto3,oneof" json:"request_expires_at_unix_millis,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GrantTimedSudoersRequest) Reset() {
	*x = GrantTimedSudoersRequest{}
	mi := &file_localbroker_v1_localbroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTimedSudoersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTimedSudoersRequest) ProtoMessage() {}

func (x *GrantTimedSudoersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localbroker_v1_localbroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTimedSudoersRequest.ProtoReflect.Descriptor instead.
func (*GrantTimedSudoersRequest) Descriptor() ([]byte, []int) {
	return file_localbroker_v1_localbroker_proto_rawDescGZIP(), []int{0}
}

func (x *GrantTimedSudoersRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *GrantTimedSudoersRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GrantTimedSudoersRequest) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

func (x *GrantTimedSudoersRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *GrantTimedSudoersRequest) GetDurationMillis() int64 {
	if x != nil {
		return x.DurationMillis
	}
	return 0
}

func (x *GrantTimedSudoersRequest) GetDeniedUsernames() []string {
	if x != nil {
		return x.DeniedUsernames
	}
	return nil
}

func (x *GrantTimedSudoersRequest) GetAllowedUidRanges() []string {
	if x != nil {
		return x.AllowedUidRanges
	}
	return nil
}

func (x *GrantTimedSudoersRequest) GetRequestExpiresAtUnixMillis() int64 {
	if x != nil && x.RequestExpiresAtUnixMillis != nil {
		return *x.RequestExpiresAtUnixMillis
	}
	return 0
}

type GrantTimedSudoersResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BrokerHandle        string                 `protobuf:"bytes,1,opt,name=broker_handle,json=brokerHandle,proto3" json:"broker_handle,omitempty"`
	TargetUsername      string                 `protobuf:"bytes,2,opt,name=target_username,json=targetUsername,proto3" json:"target_username,omitempty"`
	ExpiresAtUnixMillis int64                  `protobuf:"varint,3,opt,name=expires_at_unix_millis,json=expiresAtUnixMillis,proto3" json:"expires_at_unix_millis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GrantTimedSudoersResponse) Reset() {
	*x = GrantTimedSudoersResponse{}
	mi := &file_localbroker_v1_localbroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTimedSudoersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTimedSudoersResponse) ProtoMessage() {}

func (x *GrantTimedSudoersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localbroker_v1_localbroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTimedSudoersResponse.ProtoReflect.Descriptor instead.
func (*GrantTimedSudoersResponse) Descriptor() ([]byte, []int) {
	return file_localbroker_v1_localbroker_proto_rawDescGZIP(), []int{1}
}

func (x *GrantTimedSudoersResponse) GetBrokerHandle() string {
	if x != nil {
		return x.BrokerHandle
	}
	return ""
}

func (x *GrantTimedSudoersResponse) GetTargetUsername() string {
	if x != nil {
		return x.TargetUsername
	}
	return ""
}

func (x *GrantTimedSudoersResponse) GetExpiresAtUnixMillis() int64 {
	if x != nil {
		return x.ExpiresAtUnixMillis
	}
	return 0
}

type RevokeTimedGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerHandle  string                 `protobuf:"bytes,1,opt,name=broker_handle,json=brokerHandle,proto3" json:"broker_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTimedGrantRequest) Reset() {
	*x = RevokeTimedGrantRequest{}
	mi := &file_localbroker_v1_localbroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTimedGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTimedGrantRequest) ProtoMessage() {}

func (x *RevokeTimedGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_localbroker_v1_localbroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTimedGrantRequest.ProtoReflect.Descriptor instead.
func (*RevokeTimedGrantRequest) Descriptor() ([]byte, []int) {
	return file_localbroker_v1_localbroker_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeTimedGrantRequest) GetBrokerHandle() string {
	if x != nil {
		return x.BrokerHandle
	}
	return ""
}

type RevokeTimedGrantResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Status        RevokeTimedGrantResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=thand.localbroker.v1.RevokeTimedGrantResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTimedGrantResponse) Reset() {
	*x = RevokeTimedGrantResponse{}
	mi := &file_localbroker_v1_localbroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTimedGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTimedGrantResponse) ProtoMessage() {}

func (x *RevokeTimedGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_localbroker_v1_localbroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTimedGrantResponse.ProtoReflect.Descriptor instead.
func (*RevokeTimedGrantResponse) Descriptor() ([]byte, []int) {
	return file_localbroker_v1_localbroker_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeTimedGrantResponse) GetStatus() RevokeTimedGrantResponse_Status {
	if x != nil {
		return x.Status
	}
	return RevokeTimedGrantResponse_STATUS_UNSPECIFIED
}

var File_localbroker_v1_localbroker_proto protoreflect.FileDescriptor

const file_localbroker_v1_localbroker_proto_rawDesc = "" +
	"\n" +
	" localbroker/v1/localbroker.proto\x12\x14thand.localbroker.v1\"\x86\x03\n" +
	"\x18GrantTimedSudoersRequest\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12'\n" +
	"\x0ftarget_username\x18\x03 \x01(\tR\x0etargetUsername\x12\x1b\n" +
	"\trole_name\x18\x04 \x01(\tR\broleName\x12'\n" +
	"\x0fduration_millis\x18\x05 \x01(\x03R\x0edurationMillis\x12)\n" +
	"\x10denied_usernames\x18\x06 \x03(\tR\x0fdeniedUsernames\x12,\n" +
	"\x12allowed_uid_ranges\x18\a \x03(\tR\x10allowedUidRanges\x12G\n" +
	"\x1erequest_expires_at_unix_millis\x18\b \x01(\x03H\x00R\x1arequestExpiresAtUnixMillis\x88\x01\x01B!\n" +
	"\x1f_request_expires_at_unix_millis\"\x9e\x01\n" +
	"\x19GrantTimedSudoersResponse\x12#\n" +
	"\rbroker_handle\x18\x01 \x01(\tR\fbrokerHandle\x12'\n" +
	"\x0ftarget_username\x18\x02 \x01(\tR\x0etargetUsername\x123\n" +
	"\x16expires_at_unix_millis\x18\x03 \x01(\x03R\x13expiresAtUnixMillis\">\n" +
	"\x17RevokeTimedGrantRequest\x12#\n" +
	"\rbroker_handle\x18\x01 \x01(\tR\fbrokerHandle\"\xb5\x01\n" +
	"\x18RevokeTimedGrantResponse\x12M\n" +
	"\x06status\x18\x01 \x01(\x0e25.thand.localbroker.v1.RevokeTimedGrantResponse.StatusR\x06status\"J\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_REVOKED\x10\x01\x12\x14\n" +
	"\x10STATUS_NOT_FOUND\x10\x022\xfd\x01\n" +
	"\x12LocalBrokerControl\x12t\n" +
	"\x11GrantTimedSudoers\x12..thand.localbroker.v1.GrantTimedSudoersRequest\x1a/.thand.localbroker.v1.GrantTimedSudoersResponse\x12q\n" +
	"\x10RevokeTimedGrant\x12-.thand.localbroker.v1.RevokeTimedGrantRequest\x1a..thand.localbroker.v1.RevokeTimedGrantResponseBSZQgithub.com/thand-io/agent/internal/localbroker/proto/localbroker/v1;localbrokerv1b\x06proto3"

var (
	file_localbroker_v1_localbroker_proto_rawDescOnce sync.Once
	file_localbroker_v1_localbroker_proto_rawDescData []byte
)

func file_localbroker_v1_localbroker_proto_rawDescGZIP() []byte {
	file_localbroker_v1_localbroker_proto_rawDescOnce.Do(func() {
		file_localbroker_v1_localbroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_localbroker_v1_localbroker_proto_rawDesc), len(file_localbroker_v1_localbroker_proto_rawDesc)))
	})
	return file_localbroker_v1_localbroker_proto_rawDescData
}

var file_localbroker_v1_localbroker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_localbroker_v1_localbroker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_localbroker_v1_localbroker_proto_goTypes = []any{
	(RevokeTimedGrantResponse_Status)(0), // 0: thand.localbroker.v1.RevokeTimedGrantResponse.Status
	(*GrantTimedSudoersRequest)(nil),     // 1: thand.localbroker.v1.GrantTimedSudoersRequest
	(*GrantTimedSudoersResponse)(nil),    // 2: thand.localbroker.v1.GrantTimedSudoersResponse
	(*RevokeTimedGrantRequest)(nil),      // 3: thand.localbroker.v1.RevokeTimedGrantRequest
	(*RevokeTimedGrantResponse)(nil),     // 4: thand.localbroker.v1.RevokeTimedGrantResponse
}
var file_localbroker_v1_localbroker_proto_depIdxs = []int32{
	0, // 0: thand.localbroker.v1.RevokeTimedGrantResponse.status:type_name -> thand.localbroker.v1.RevokeTimedGrantResponse.Status
	1, // 1: thand.localbroker.v1.LocalBrokerControl.GrantTimedSudoers:input_type -> thand.localbroker.v1.GrantTimedSudoersRequest
	3, // 2: thand.localbroker.v1.LocalBrokerControl.RevokeTimedGrant:input_type -> thand.localbroker.v1.RevokeTimedGrantRequest
	2, // 3: thand.localbroker.v1.LocalBrokerControl.GrantTimedSudoers:output_type -> thand.localbroker.v1.GrantTimedSudoersResponse
	4, // 4: thand.localbroker.v1.LocalBrokerControl.RevokeTimedGrant:output_type -> thand.localbroker.v1.RevokeTimedGrantResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_localbroker_v1_localbroker_proto_init() }
func file_localbroker_v1_localbroker_proto_init() {
	if File_localbroker_v1_localbroker_proto != nil {
		return
	}
	file_localbroker_v1_localbroker_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_localbroker_v1_localbroker_proto_rawDesc), len(file_localbroker_v1_localbroker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_localbroker_v1_localbroker_proto_goTypes,
		DependencyIndexes: file_localbroker_v1_localbroker_proto_depIdxs,
		EnumInfos:         file_localbroker_v1_localbroker_proto_enumTypes,
		MessageInfos:      file_localbroker_v1_localbroker_proto_msgTypes,
	}.Build()
	File_localbroker_v1_localbroker_proto = out.File
	file_localbroker_v1_localbroker_proto_goTypes = nil
	file_localbroker_v1_localbroker_proto_depIdxs = nil
}
