// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: localbroker/v1/localbroker.proto

package localbrokerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalBrokerControl_GrantTimedSudoers_FullMethodName = "/thand.localbroker.v1.LocalBrokerControl/GrantTimedSudoers"
	LocalBrokerControl_RevokeTimedGrant_FullMethodName  = "/thand.localbroker.v1.LocalBrokerControl/RevokeTimedGrant"
)

// LocalBrokerControlClient is the client API for LocalBrokerControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocalBrokerControlClient interface {
	GrantTimedSudoers(ctx context.Context, in *GrantTimedSudoersRequest, opts ...grpc.CallOption) (*GrantTimedSudoersResponse, error)
	RevokeTimedGrant(ctx context.Context, in *RevokeTimedGrantRequest, opts ...grpc.CallOption) (*RevokeTimedGrantResponse, error)
}

type localBrokerControlClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalBrokerControlClient(cc grpc.ClientConnInterface) LocalBrokerControlClient {
	return &localBrokerControlClient{cc}
}

func (c *localBrokerControlClient) GrantTimedSudoers(ctx context.Context, in *GrantTimedSudoersRequest, opts ...grpc.CallOption) (*GrantTimedSudoersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantTimedSudoersResponse)
	err := c.cc.Invoke(ctx, LocalBrokerControl_GrantTimedSudoers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localBrokerControlClient) RevokeTimedGrant(ctx context.Context, in *RevokeTimedGrantRequest, opts ...grpc.CallOption) (*RevokeTimedGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTimedGrantResponse)
	err := c.cc.Invoke(ctx, LocalBrokerControl_RevokeTimedGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalBrokerControlServer is the server API for LocalBrokerControl service.
// All implementations must embed UnimplementedLocalBrokerControlServer
// for forward compatibility.
type LocalBrokerControlServer interface {
	GrantTimedSudoers(context.Context, *GrantTimedSudoersRequest) (*GrantTimedSudoersResponse, error)
	RevokeTimedGrant(context.Context, *RevokeTimedGrantRequest) (*RevokeTimedGrantResponse, error)
	mustEmbedUnimplementedLocalBrokerControlServer()
}

// UnimplementedLocalBrokerControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalBrokerControlServer struct{}

func (UnimplementedLocalBrokerControlServer) GrantTimedSudoers(context.Context, *GrantTimedSudoersRequest) (*GrantTimedSudoersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantTimedSudoers not implemented")
}
func (UnimplementedLocalBrokerControlServer) RevokeTimedGrant(context.Context, *RevokeTimedGrantRequest) (*RevokeTimedGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeTimedGrant not implemented")
}
func (UnimplementedLocalBrokerControlServer) mustEmbedUnimplementedLocalBrokerControlServer() {}
func (UnimplementedLocalBrokerControlServer) testEmbeddedByValue()                            {}

// UnsafeLocalBrokerControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalBrokerControlServer will
// result in compilation errors.
type UnsafeLocalBrokerControlServer interface {
	mustEmbedUnimplementedLocalBrokerControlServer()
}

func RegisterLocalBrokerControlServer(s grpc.ServiceRegistrar, srv LocalBrokerControlServer) {
	// If the following call panics, it indicates UnimplementedLocalBrokerControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalBrokerControl_ServiceDesc, srv)
}

func _LocalBrokerControl_GrantTimedSudoers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantTimedSudoersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalBrokerControlServer).GrantTimedSudoers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalBrokerControl_GrantTimedSudoers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalBrokerControlServer).GrantTimedSudoers(ctx, req.(*GrantTimedSudoersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalBrokerControl_RevokeTimedGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTimedGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalBrokerControlServer).RevokeTimedGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalBrokerControl_RevokeTimedGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalBrokerControlServer).RevokeTimedGrant(ctx, req.(*RevokeTimedGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalBrokerControl_ServiceDesc is the grpc.ServiceDesc for LocalBrokerControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalBrokerControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thand.localbroker.v1.LocalBrokerControl",
	HandlerType: (*LocalBrokerControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrantTimedSudoers",
			Handler:    _LocalBrokerControl_GrantTimedSudoers_Handler,
		},
		{
			MethodName: "RevokeTimedGrant",
			Handler:    _LocalBrokerControl_RevokeTimedGrant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "localbroker/v1/localbroker.proto",
}
